id: I0004
imported: 2023-04-07 22:05:31.361938
last_modified: 2023-04-07 22:05:31.361949
source_metadata:
  pub_name: PK
bases:
  EF79:
    source_metadata: {}
    order: 1
    base_file: EF79.txt
copyright:
  status: Unknown
  notice: ''
