id: I0001
imported: 2023-04-07 22:05:31.312051
last_modified: 2023-04-07 22:05:31.312071
source_metadata:
  pub_name: CO
bases:
  EF79:
    source_metadata: {}
    order: 1
    base_file: EF79.txt
copyright:
  status: Unknown
  notice: ''
